appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: J4YMm3xoOzL5a56n0nQq2Z51yCopk+0tY5TTX8EGPLaf7x3WLhjZ2nYqpWVI7s02yVLmTur5CwbvUjJIfoApu9f6IqoAzz9rqCiZp55TFHFJeoZKMLtpQHRj9eckyeETBdeqM8Pt+An1k+eCqeKFsnonnhhssO+hbs04qGXdUdjPEVGjZ8k4p+PGvhexbFqGkMFPWwYVjoqt3hloC6VpZTbxh/Cp7eHTVwjPJaNVY68mQp6vMw9ZU2MsaNg0ojxI5ZUa9YgVxwTfd4M2/W7GieDGZBB0ja3PoJmcSzNkgz8oCmMWyz+NHME15XPLE+p3cdhMtmiWSQcrr3nLycX/DoJ2vjXFdIYNDrM7Q8o+Ip/PRgykrSvF55c0/wM20hf/1ir4LSVGd+1UMoO1x+WezL90UviajbDgG4eaaoVSgl5Y2h+gpdSpARZYRvZSMe02GXf6pMhvPeGmgEmzFxKtZCA1UpoQ23WXS03UBpbo8QvI5wGsNCLIQEcPNQNqII1yvI6P35IMKXl95YuiRxc4FyqonZUUNEOrsPk2FmuW9S6GhIX4bacQ3EcQf/dEaFywhtK7AAfLPG0aBuoGlvR2x5a/Mlj8dkbChoAyZbnKeqy8zsWgk13Wgx7+aM9gDJirtxJkIDckeroxAt8S7Oqo7SzvT413tpno+cpfDtxUoPg=}
